#==================================
# = Datasource
#==================================
spring.datasource.url=jdbc:postgresql://localhost:5432/siwfootball
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql=trace

spring.jpa.hibernate.ddl-auto=create

#==================================
# = Webserver
#==================================
server.port=8080